@startuml プリンタ
left to right direction
state プリンタ{
    state entry <<entrypoint>>
    state exit <<exitpoint>>
    entry --> 待機中
    待機中 --> 印刷中
    印刷中 -up-> 用紙なし
    用紙なし --> 待機中
    印刷中 -down-> exit
}
[*] --> entry
exit --> [*]
@enduml