@startuml 診察予約システム
    [*] -right-> メニュー
    メニュー -down-> 予約と確認 : 予約と確認へを押す
    予約と確認 -up-> メニュー : 名前か電話番号を入力してから\n取り消しボタンを押す
    あなたの順番 -up-> メニュー : メニューボタンを\n押す
    予約と確認 -right-> あなたの順番 : 登録ボタンを\n押す
    予約と確認 -right-> あなたの順番 : 確認ボタンを\n押す
    メニュー -down-> 今の順番 : 今の順番へを押す
    今の順番 -up-> メニュー : メニューへを押す
    メニュー -right-> [*]
@enduml