@startuml カレー
title バターチキンカレー
start
:スーパーで食材を調達する;
:食材を洗う;
fork
:食材を切る;
:一口大に切った鶏むね肉をボウルに入れる;
fork
:鶏むね肉を冷蔵庫で冷やす;
->1時間程度;
fork again
:フライパンにバター,カレー粉,おろしショウガ,おろしニンニクを入れて炒める;
->バター60g,カレー粉大さじ1杯,ショウガとニンニク小さじ1,弱火で1分程炒める;
:カットトマトを400g入れ,弱火の中火でふつふつするまで温める;
end fork
:鶏むね肉を加えて木べらで混ぜながら弱めの中火で温める;
fork again
:米を炊く;
end fork
:肉の中まで火が通ったら生クリーム,砂糖,塩を加えて出来上がり;
->生クリーム200ml,砂糖大さじ3杯,塩大さじ1杯;
note right
お好みでスジャータやコーヒーフレッシュを入れてアクセントに
endnote
:カレーライス]
stop
@enduml